language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libboost-test-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -f Makefile.osx test; else make test; fi

